### ISSUE TITLE
No usage details in root URL

### ISSUE THREAD

**Issue by scraperdragon** [jgarber623/spaceholder.cc#6]
At the url http://spaceholder.cc/ I'd expect to see a reference to a sample image, e.g. `http://spaceholder.cc/123x456`, or at least saying that the usage is documented on GitHub.

`/app/views/index.erb` will probably populate this, but it's currently empty. Taking text from the README.md is probably an excellent plan.

**Comment by jgarber623** [comment]
@scraperdragon You nailed it! This is/was on my mental to-do list. Much better having it in GitHub. Thanks!

**Comment by jgarber623** [comment]
#9 resolved this. We've got content on the homepage!
